version: '3'

networks:
    back:

services:
    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        build:
            dockerfile: .infra/docker/mysql/Dockerfile
            context: .
        networks:
            - back
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_DATABASE_TEST: ${DATABASE_NAME}_test
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        security_opt: #fix mbind not permitted in container
            - seccomp:unconfined
        healthcheck:
            test: "mysql --user=root --password=${DATABASE_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
            interval: 3s
            timeout: 1s
            retries: 5

    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        image: nginx:latest
        networks:
            - back
        links:
            - php
        volumes:
            - ./.infra/docker/nginx:/etc/nginx/conf.d:delegated
            - .:/app:delegated
        working_dir: /app
        ports:
            - 8666:80
        environment:
            NGINX_SERVERNAME: ${APP_DOMAIN}
            NGINX_ROOTDIR: /app/public
        command: /bin/bash -c "envsubst '$$NGINX_SERVERNAME $$NGINX_ROOTDIR' < /etc/nginx/conf.d/beer.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php
        build:
            dockerfile: .infra/docker/php/Dockerfile
            context: .
        networks:
            - back
        working_dir: /app
        volumes:
            - .:/app
        user: 1000:www-data
        environment:
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            APP_DOMAIN: ${APP_DOMAIN}
